#!/bin/bash
# Install base packages for a minimal Linux desktop

set -o errexit

# Basic packages and Window manager
sudo apt install \
     apt-listbugs \
     bluez \
     brightnessctl \
     build-essential \
     emacs \
     eog \
     evince \
     flameshot \
     foot \
     gammastep \
     gimp \
     git \
     inkscape \
     inotify-tools \
     jq \
     nautilus \
     network-manager \
     pandoc \
     pass \
     python3-pydbus \
     rsync \
     shellcheck \
     sway \
     swaybg \
     swayidle \
     swaylock \
     texlive-fonts-extra \
     texlive-latex-extra \
     xdg-desktop-portal-wlr \
     xdg-utils \
     xwayland \
     ydotool

# Packages required for using yubikey
sudo apt install gnupg2 dirmngr pcscd scdaemon
gpg --recv-keys 4E7DA7B5A0F86992D6EB3F514601878662E33372
gpg --card-status