#!/bin/bash
# Install VSCode and a selection of packages
set -o errexit

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/microsoft-archive-keyring.gpg
sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

sudo apt-get update
sudo apt-get install code


# you can list all currently installed extensions with: `code --list-extensions`
extensions=(
     kahole.magit
     stkb.rewrap
)
for extension in "${extensions[@]}"; do
     code --install-extension "$extension"
done
