#!/bin/bash

is_blocked() {
    /usr/sbin/rfkill list bluetooth --output SOFT,HARD --noheadings \
	| grep -w blocked --quiet
}

if [[ -n $BLOCK_BUTTON ]]; then
    if is_blocked; then
	/usr/sbin/rfkill unblock bluetooth
    else
	/usr/sbin/rfkill block bluetooth
    fi
fi

if is_blocked; then
    echo "OFF"
    echo "blocked"
else
    echo "ON"
    echo "unblocked"
fi
