#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2016 Jakob Odersky <jakob@odersky.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

# color if load is too high
awk -v cpus=$cpus -v cpuload=$load '
    BEGIN {
        load_percent=(cpuload*100)/cpus
        print cpuload
        print cpuload
        if (load_percent < 10) {
            exit 0;
        } else if (load_percent < 50) {
            print "#00ff00";
            exit 0;
        } else if (load_percent < 80) {
            print "#ffff00";
            exit 0;
        } else {
            print "#ff0000";
            exit 0;
        }
    }
'
