#!/bin/bash

power0=$(cat "/sys/class/power_supply/BAT0/power_now")
power1=$(cat "/sys/class/power_supply/BAT1/power_now")
power=$(( power0 + power1 ))

printf '%0.1fW\n' "$(( power ))e-6"
printf '%0.1fW\n' "$(( power ))e-6"

exit 0
