#!/bin/bash

power0=$(cat "/sys/class/power_supply/BAT0/power_now")
power1=$(cat "/sys/class/power_supply/BAT1/power_now")
power=$(( power0 + power1 ))

energy0=$(cat "/sys/class/power_supply/BAT0/energy_now")
energy1=$(cat "/sys/class/power_supply/BAT1/energy_now")
energy=$(( energy0 + energy1 ))

mw=$(( power / 1000))
mwh=$(( energy / 1000))

echo "${mw}mW / ${mwh}mWh"
echo "${mw}mW / ${mwh}mWh"

exit 0
