#!/bin/bash

systemd_status() {
    instance="$1"
    unit="$2"
    icon="$3"
    color="$4"

    case $(systemctl "$instance" is-active "$unit") in
        active | activating)
            echo "<span foreground=\"$color\">$icon</span>"
            ;;
        *)
            if systemctl "$instance" --quiet is-failed "$unit"; then
                echo "<span foreground=\"#ff0000\">$icon</span>"
            elif ! systemctl "$instance" --quiet is-enabled "$unit"; then
                # unknown and disabled units are not displayed at all
                # (note that !enabled includes units which have not been found)
                true
            else
                # inactive units (found, not failed and not disabled) are greyed out
                echo "<span foreground=\"#464f63\">$icon</span>"
                true
            fi
            ;;
    esac
}


status=""
#status='<span foreground="blue" size="x-large">Blue text</span> is <i>cool</i>!'
#status="      |"

#status=""
#
status+="$(systemd_status --system resteasy.service  orange) "
status+="$(systemd_status --user internet-metered.target  orange) "
#status+="$(systemd_status --user prometheus.service P green) "
#status+="$(systemd_status --user grafana.service G green) "
#status+="$(systemd_status backup.timer ) "
#status+="$(systemd_status backup.service ) "
#status+="$(systemd_status backupz.service )"

echo "$status"
echo "$status"
