#!/bin/sh

status=$(qdbus org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get org.mpris.MediaPlayer2.Player PlaybackStatus | tr '[:upper:]' '[:lower:]')

case $status in
    playing)
	echo 
	;;
    paused)
	echo 
	;;
    *)
	echo 
	;;
esac
