#!/bin/bash

set -o errexit

ssid="$(iwgetid -r)"

if [[ $ssid == speakeasy ]]; then
  data="$(curl http://10.240.0.10/metrics -Ss)"
  temp="$(echo "$data" | grep temperature_celsius | cut -d' ' -f 2)"
  rh="$(echo "$data" | grep relative_humidity_percent | cut -d' ' -f 2)"
  echo "${temp}°C ${rh}%"
  echo "${temp}°C ${rh}%"
else
  echo "unavailable"
  echo "unavailable"
fi
