#!/bin/bash
set -e

device="/sys/class/power_supply/${1:-BAT0}"
status=$(cat "$device/status")
percent=$(cat "$device/capacity")
energy=$(cat "$device/energy_now")

status_text=""
if [[ $status = "Discharging" ]]; then
    status_text=""
elif [[ $status = "Charging" ]]; then
    status_text=" "
fi

class=""
# consider color and urgent flag only on discharge
if [[ $status = "Discharging" ]]; then
    if [[ $percent -le 15 ]]; then
	    class="urgent";
    fi
    if [[ $percent -le 5 ]]; then
        class="critical";
    fi
fi

/usr/bin/printf '{"text": "%i%% (%0.1fWh)%s", "class": "%s"}' \
       "$(( percent ))" \
       "$(( energy ))e-6" \
       "$status_text" \
       "$class"

exit 0
