#!/bin/bash

power=0
for bat in /sys/class/power_supply/BAT*; do
    p=$(cat "$bat/power_now")
    power=$((power+p))
done

/usr/bin/printf '%0.1fW\n' "$(( power ))e-6"
/usr/bin/printf '%0.1fW\n' "$(( power ))e-6"

exit 0
